apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault-secret-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<key-vault-managed-identity-client-id>"
    keyvaultName: "<your-key-vault-name>"
    objects: |
      array:
      - |
        objectName: secret1
        objectType: secret
        objectVersion: ""
    tenantId: "<your-azure-tenant-id>"
